# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('book', 'book'), ('comics', 'comics'), ('manga', 'manga'), ('e-book', 'e-book')], max_length=30)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('SCI-FI', 'SCI-FI'), ('horror', 'horror')], max_length=50)),
                ('describe', models.CharField(max_length=1000)),
                ('isbn', models.CharField(max_length=17)),
                ('highlighted', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LendBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lend', models.DateField()),
                ('date_end_lend', models.DateField()),
                ('give_up', models.BooleanField(default=False)),
                ('highlighted', models.TextField()),
                ('idB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Book')),
                ('idU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
